language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: APOHsSUYdUAob3uMPb480cUrcKXJFvQzIzCGqpGfqnZHQunCsweFDa64IBR2y+pXkdTpxKFne6ePZlnnL76GBrdmDg7V2VwIVfgw9WB+YTB3m2Zo0uirITxony3NcEZFH9fawEiJGwfT1IfIKxKyYzmwHqj5rI/ubFZYolsMPXbmiAfP3Q+bvHN0DVZX6DgLgzOOcWra8M4pRHy/1M1NVJZfvEpIaFCiHIV9PHIZP01LuR0526/hjtGG68tCT1OGyiZP/fXqk2gbllVXwk8DEuRq2KD6pwpX0ItUH+zOdZYbB7dODfByOMlGmUc6UBP56+rOXsvQBeneD6g999hb2+n55lDCoE/99TnEbqhBhbVeV5T+kTxF8pPK3XPVvQSPfPGQefHWMmi+QWT82TrQj4Y+nxq4MqM8z3ZlmzEFxnnJrbsCLut10PG5ViB5iHmI8c15oAjdsxO+MDDJrKBPBQOxtjlVMCWAxDf5wnlJS79fzdkFqw+YauF2mAdTKJUBNP38fn0hvkgdBdLbhLNqjR+OVFJMgQK1o3j9bp2+ckbW1ZF9JEzvreuYbDAETaHr/UVNwphTEQg8BYVtQTjB+1sBhKywO/J9VOtx25eEb4oqfRLl/kjYlh4JuwACS0O7AXnnVg3IrBklNkBZ0r9wcQxH3/89eryh/k010aj9gEU=
  file:
    - fs.img
    - xv6.img
  skip_cleanup: true
  on:
    repo: vicho2t/xv6-public
    branch: project_3
    tags: true